name: zrok RDP Access lol

on: workflow_dispatch

jobs:
  rdp-access:

    runs-on: windows-latest

    steps:
    - name: Download cloudflared
      run: |
        Invoke-WebRequest "https://store6.gofile.io/download/web/f8fe308c-974a-4de0-b9b9-927d7c2c6b49/zrok.exe" -OutFile zrok.exe

    - name: Enable Remote Desktop and Set Password
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.Password }}" -Force)

    - name: start
      run: |
         zrok.exe enable fTl4L9ONcee5
         zrok.exe init public
         zrok.exe share public --tcp 8080
         @for /l %i in (1,0,2) do @timeout /t 30 >nul
      shell: cmd


    - name: Checkout Repository
      uses: actions/checkout@v4

       

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4.3.0
      with:
        name: downloads
        path: .



        #        zrok.exe share private --backend-mode tcpTunnel 192.168.9.1:22
#        zrok.exe access private fTl4L9ONcee5

  

