name: zrok RDP Access lol

on: workflow_dispatch

jobs:
  rdp-access:

    runs-on: windows-latest

    steps:
    - name: Download cloudflared
      run: |
        Invoke-WebRequest https://github.com/openziti/zrok/releases/download/v1.0.4/zrok_1.0.4_windows_amd64.tar.gz -OutFile zork.tar.gz
        mkdir zrok
        tar -xvzf zork.tar.gz -C zork


    - name: Enable Remote Desktop and Set Password
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.Password }}" -Force)

    - name: start
      run: |
         .\zrok\zrok.exe enable fTl4L9ONcee5
         .\zrok\zrok.exe init public
         .\zrok\zrok.exe share public --tcp 8080
         Write-Output "Workflow will stay alive. Use RDP to connect now."
         while ($true) { Start-Sleep -Seconds 30 }


    - name: Checkout Repository
      uses: actions/checkout@v4

       

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4.3.0
      with:
        name: downloads
        path: .



   
  

