name: Cloudflare RDP Access

on: workflow_dispatch

jobs:
  rdp-access:

    runs-on: windows-latest

    steps:
    - name: Download cloudflared
      run: |
        Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

    - name: Enable Remote Desktop and Set Password
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.Password }}" -Force)

    - name: Start Cloudflared Tunnel (TCP on port 3389)
      run: |
        Start-Process -FilePath ".\cloudflared.exe" -ArgumentList "tunnel", "--url", "tcp://localhost:3389", "--logfile", "log.txt" -NoNewWindow
        Start-Sleep -Seconds 10
        $log = Get-Content log.txt
        $rdpLine = $log | Where-Object { $_ -match "trycloudflare.com" } | Select-Object -First 1
        if ($rdpLine -match "https://(.*).trycloudflare.com") {
          $hostname = $matches[1] + ".trycloudflare.com"
          echo '=============================='
          echo " RDP Tunnel: $hostname"
          echo ' USER: runneradmin'
          echo ' PASSWORD: from secrets.Password'
          echo '=============================='
        } else {
          echo " Could not extract tunnel URL from logs."
        }
      shell: powershell

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4.3.0
      with:
        name: downloads
        path: .

  


